spring:
  application:
    name: wishlist-service
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/wishlist
server:
  port: 8082
management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always