spring:
  application:
    name: wishlist-service
  data:
    mongodb:
#      uri: mongodb://localhost:27017/wishlist
      uri: mongodb://mongo:27017/wishlist
server:
  port: 8080
management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always